# Generated by Django 4.2.1 on 2023-06-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="contact"),
        ),
    ]
